const mongoose=require("mongoose");
const appointmentSchema=new mongoose.Schema({
    patientName:{
        type:String,
        required:true
    },
    patientEmail:{
        type:String,
        required:true
    },
    patientPhone:{
        type:String,
        required:true
    },
    doctorName:{
        type:String,
        required:true
    },
    doctorEmail:{
        type:String,
        required:true
    },
    doctorPhone:{
        type:String,
        required:true
    },
    specialization:{
        type:String,
        required:true
    },
    fees:{
        type:String,
        required:true
    },
    date:{
        type:String,
        required:true
    },
    time:{
        type:String,
        required:true
    },
    status:{
        type:String,
        default:"Active"
    },
    via:{
        type:String,
        default:"None"
    }
})
const appointments=mongoose.model("appointments",appointmentSchema);
module.exports=appointments;